[pytest]
log_file = logs/pytest.log
log_file_level = INFO
log_file_format = %(asctime)s - %(levelname)s - %(filename)s:%(lineno)d - %(message)s
log_file_date_format = %Y-%m-%d %H:%M:%S
log_cli = true
log_cli_level = INFO
; 禁掉 result-log 插件
addopts = -vs --alluredir=temps --clean-alluredir -p no:result_log
pythonpath = .
; addopts= -vs
python_files = Test*.py
python_classes = Test
python_functions = test*
markers =
    login :登录模块
    AddBook :添加图书
    Bookshelf :最近阅读
    RecentReading :最近阅读
    Space :评价图书
